[2024-12-04T19:49:58.462+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator_test.hello manual__2024-12-04T19:49:57.355934+00:00 [queued]>
[2024-12-04T19:49:58.472+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator_test.hello manual__2024-12-04T19:49:57.355934+00:00 [queued]>
[2024-12-04T19:49:58.472+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-04T19:49:58.472+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-04T19:49:58.472+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-04T19:49:58.486+0000] {taskinstance.py:1383} INFO - Executing <Task(joeloperator): hello> on 2024-12-04 19:49:57.355934+00:00
[2024-12-04T19:49:58.494+0000] {standard_task_runner.py:55} INFO - Started process 1460 to run task
[2024-12-04T19:49:58.498+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customoperator_test', 'hello', 'manual__2024-12-04T19:49:57.355934+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/custom_operator_dag.py', '--cfg-path', '/tmp/tmpm0b8tif_']
[2024-12-04T19:49:58.498+0000] {standard_task_runner.py:83} INFO - Job 48: Subtask hello
[2024-12-04T19:49:58.559+0000] {task_command.py:376} INFO - Running <TaskInstance: customoperator_test.hello manual__2024-12-04T19:49:57.355934+00:00 [running]> on host 308becaf7165
[2024-12-04T19:49:58.637+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customoperator_test
AIRFLOW_CTX_TASK_ID=hello
AIRFLOW_CTX_EXECUTION_DATE=2024-12-04T19:49:57.355934+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-04T19:49:57.355934+00:00
[2024-12-04T19:49:58.637+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1127, in execute
    raise NotImplementedError()
NotImplementedError
[2024-12-04T19:49:58.647+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=customoperator_test, task_id=hello, execution_date=20241204T194957, start_date=20241204T194958, end_date=20241204T194958
[2024-12-04T19:49:58.658+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 48 for task hello (; 1460)
[2024-12-04T19:49:58.709+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-04T19:49:58.728+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
